import "../globals.css";
import { Poppins } from "@next/font/google";
const poppins = Poppins({ weight: "400" });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.className}>
      <head>
        <title>Landify | Academy of your business.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="bg-white ">{children}</body>
    </html>
  );
}
